spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 30000
      max-lifetime: 1800000
  cache:
    type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mail:
    username: wqk2303840221@163.com
    host: smtp.163.com
    password: PLRsbXrfgivPCXRq
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '管理员端'
      paths-to-match: '/**'
      packages-to-scan: com.example.shopping.controller.admin
    - group: '客户端'
      paths-to-match: '/**'
      packages-to-scan: com.example.shopping.controller.user
#MinIO的配置
minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: my-bucket